language: haskell
install: cabal update && cabal install pandoc
cache: cabal
script: make
notifications:
  email:
    on_success: always
    on_failure: always
after_success: bash .ci/update_pages.sh
env:
  global:
    secure: CzE3x2pGxUqqlB9jCHIFFA7w1+V+PNMOnhHtNSpNDc0azI/vdATfqnWascucStif4isV9QX+517eJG/mVW+8GzxH5qvIS4GzbayaECRHT2DMKuUEHvHc3LsPyQuPQkkBjWfDLx2HgwwzWEztD/Lo03CRaYBnQMWNqB+po8Xht6U=
